import { v4 as uuidv4 } from "uuid";
import type { Template } from "@/types";

export const BUILT_IN_TEMPLATES: Template[] = [
  {
    id: "swe",
    name: "Software Engineer",
    profession: "Software Engineering",
    description: "Full-stack or backend engineer template with project highlights and technical skills.",
    icon: "💻",
    color: "from-indigo-500 to-cyan-500",
    tags: ["Backend", "Frontend", "Full Stack"],
    resumeData: {
      personalInfo: {
        name: "Alex Johnson",
        email: "alex.johnson@email.com",
        phone: "+1 (555) 123-4567",
        location: "San Francisco, CA",
        linkedin: "https://linkedin.com/in/alexjohnson",
        github: "https://github.com/alexjohnson",
        website: "https://alexjohnson.dev",
      },
      summary: "Results-driven Software Engineer with 4+ years of experience building scalable distributed systems and high-performance web applications. Passionate about clean architecture and developer experience.",
      experience: [
        {
          id: uuidv4(),
          company: "TechCorp Inc.",
          position: "Senior Software Engineer",
          location: "San Francisco, CA",
          startDate: "Jan 2022",
          endDate: "",
          current: true,
          description: [
            "Architected and implemented microservices platform serving 10M+ daily active users, reducing latency by 40%",
            "Led migration from monolith to event-driven architecture using Kafka and Kubernetes, improving deployment frequency by 3x",
            "Mentored 5 junior engineers and established code review culture, reducing bug escape rate by 35%",
          ],
        },
        {
          id: uuidv4(),
          company: "StartupXYZ",
          position: "Software Engineer",
          location: "Remote",
          startDate: "Jun 2020",
          endDate: "Dec 2021",
          current: false,
          description: [
            "Built real-time collaborative editor using WebSockets and CRDTs, supporting 1000+ concurrent users",
            "Reduced database query times by 60% through strategic indexing and query optimization",
            "Implemented CI/CD pipeline with GitHub Actions, cutting release time from 2 hours to 15 minutes",
          ],
        },
      ],
      education: [
        {
          id: uuidv4(),
          institution: "University of California, Berkeley",
          degree: "Bachelor of Science",
          field: "Computer Science",
          location: "Berkeley, CA",
          startDate: "Aug 2016",
          endDate: "May 2020",
          gpa: "3.8/4.0",
          courses: ["Data Structures", "Algorithms", "Operating Systems", "Distributed Systems"],
        },
      ],
      skills: {
        Languages: ["Python", "TypeScript", "Go", "Rust", "Java"],
        Frameworks: ["Next.js", "FastAPI", "Spring Boot", "gRPC", "GraphQL"],
        "Cloud & DevOps": ["AWS", "GCP", "Docker", "Kubernetes", "Terraform"],
        Databases: ["PostgreSQL", "Redis", "Cassandra", "MongoDB"],
      },
      projects: [
        {
          id: uuidv4(),
          name: "OpenSearch Engine",
          description: "Distributed full-text search engine",
          technologies: ["Go", "Raft consensus", "BoltDB"],
          github: "https://github.com/alexjohnson/opensearch",
          bullets: [
            "Built distributed search engine from scratch using Raft consensus algorithm for fault tolerance",
            "Achieved 50k queries/second with sub-10ms p99 latency on commodity hardware",
          ],
        },
      ],
      certifications: [
        {
          id: uuidv4(),
          name: "AWS Solutions Architect - Professional",
          issuer: "Amazon Web Services",
          date: "2023",
        },
      ],
      sectionOrder: ["summary", "experience", "education", "projects", "skills", "certifications"],
    },
  },
  {
    id: "ml",
    name: "ML / AI Engineer",
    profession: "Machine Learning",
    description: "Research-oriented template with publications, model metrics, and ML pipeline experience.",
    icon: "🤖",
    color: "from-violet-500 to-pink-500",
    tags: ["Deep Learning", "NLP", "Computer Vision"],
    resumeData: {
      personalInfo: {
        name: "Priya Sharma",
        email: "priya.sharma@email.com",
        phone: "+1 (555) 987-6543",
        location: "Seattle, WA",
        linkedin: "https://linkedin.com/in/priyasharma",
        github: "https://github.com/priyasharma",
        website: "https://priyasharma.ai",
      },
      summary: "ML Engineer with expertise in large language models, computer vision, and production ML systems. Published researcher with 3 papers at top-tier venues (NeurIPS, ICML).",
      experience: [
        {
          id: uuidv4(),
          company: "AI Research Lab",
          position: "Senior ML Engineer",
          location: "Seattle, WA",
          startDate: "Mar 2022",
          endDate: "",
          current: true,
          description: [
            "Fine-tuned LLaMA-3 70B on domain-specific corpora, achieving 15% improvement over GPT-4 on internal benchmarks",
            "Built end-to-end ML pipeline (data ingestion → training → evaluation → serving) handling 5TB daily data",
            "Reduced model inference latency by 3x using quantization (INT8) and TensorRT optimization",
          ],
        },
        {
          id: uuidv4(),
          company: "DeepVision Inc.",
          position: "Machine Learning Engineer",
          location: "San Jose, CA",
          startDate: "Jul 2020",
          endDate: "Feb 2022",
          current: false,
          description: [
            "Developed real-time object detection system achieving 95% mAP on custom dataset using YOLOv8",
            "Implemented data augmentation pipeline increasing model robustness by 20% on out-of-distribution data",
          ],
        },
      ],
      education: [
        {
          id: uuidv4(),
          institution: "Stanford University",
          degree: "Master of Science",
          field: "Computer Science (AI track)",
          location: "Stanford, CA",
          startDate: "Sep 2018",
          endDate: "Jun 2020",
          gpa: "3.9/4.0",
          courses: ["Deep Learning", "NLP", "Probabilistic Graphical Models", "Reinforcement Learning"],
        },
      ],
      skills: {
        "ML Frameworks": ["PyTorch", "TensorFlow", "JAX", "Hugging Face Transformers", "LangChain"],
        Languages: ["Python", "CUDA C++", "Julia", "R"],
        "MLOps & Infra": ["MLflow", "Weights & Biases", "Ray", "Kubeflow", "DVC"],
        "Cloud & Data": ["AWS SageMaker", "GCS", "Spark", "Apache Kafka"],
      },
      projects: [
        {
          id: uuidv4(),
          name: "FinBERT-RAG",
          description: "Retrieval-augmented financial Q&A system",
          technologies: ["PyTorch", "FAISS", "LangChain", "FastAPI"],
          github: "https://github.com/priyasharma/finbert-rag",
          bullets: [
            "Built RAG system over 10M financial documents, achieving 89% accuracy on FinQA benchmark",
            "Deployed as production API serving 500+ queries/day with sub-500ms response time",
          ],
        },
      ],
      certifications: [],
      publications: [
        {
          id: uuidv4(),
          title: "Efficient Fine-tuning of Large Language Models via Adaptive LoRA",
          venue: "NeurIPS 2023",
          date: "Dec 2023",
          url: "https://arxiv.org/abs/2312.00000",
        },
      ],
      sectionOrder: ["summary", "experience", "education", "projects", "skills", "certifications"],
    },
  },
  {
    id: "devops",
    name: "DevOps / SRE",
    profession: "DevOps & Cloud",
    description: "Infrastructure-focused template highlighting cloud, reliability, and automation expertise.",
    icon: "⚙️",
    color: "from-orange-500 to-yellow-500",
    tags: ["Kubernetes", "CI/CD", "Cloud"],
    resumeData: {
      personalInfo: {
        name: "Marcus Chen",
        email: "marcus.chen@email.com",
        phone: "+1 (555) 246-8135",
        location: "Austin, TX",
        linkedin: "https://linkedin.com/in/marcuschen",
        github: "https://github.com/marcuschen",
        website: "",
      },
      summary: "Senior DevOps Engineer with 6+ years building and maintaining large-scale cloud infrastructure. Specializing in Kubernetes, observability, and platform engineering.",
      experience: [
        {
          id: uuidv4(),
          company: "CloudScale Corp",
          position: "Senior Site Reliability Engineer",
          location: "Austin, TX",
          startDate: "Feb 2021",
          endDate: "",
          current: true,
          description: [
            "Managed 200+ node Kubernetes cluster serving 50M requests/day with 99.99% uptime SLA",
            "Implemented GitOps workflow with ArgoCD, reducing deployment failures by 80%",
            "Built observability platform (Prometheus/Grafana/Loki) reducing MTTR from 2 hours to 15 minutes",
          ],
        },
      ],
      education: [
        {
          id: uuidv4(),
          institution: "Texas A&M University",
          degree: "Bachelor of Science",
          field: "Computer Engineering",
          location: "College Station, TX",
          startDate: "Aug 2014",
          endDate: "May 2018",
          gpa: "",
          courses: [],
        },
      ],
      skills: {
        "Container & Orchestration": ["Kubernetes", "Docker", "Helm", "ArgoCD", "Istio"],
        "CI/CD": ["GitHub Actions", "Jenkins", "GitLab CI", "Tekton", "Spinnaker"],
        "Cloud Platforms": ["AWS (EKS, ECS, Lambda)", "GCP (GKE)", "Azure (AKS)", "Terraform"],
        "Monitoring & Logging": ["Prometheus", "Grafana", "Loki", "Datadog", "ELK Stack"],
        Languages: ["Python", "Bash", "Go", "HCL"],
      },
      projects: [
        {
          id: uuidv4(),
          name: "K8s Cost Optimizer",
          description: "Automated Kubernetes cost optimization tool",
          technologies: ["Go", "Kubernetes API", "Prometheus"],
          github: "https://github.com/marcuschen/k8s-cost-optimizer",
          bullets: [
            "Built automated right-sizing tool that reduced cloud spend by $200k/year",
            "Implemented spot instance management saving an additional 40% on compute costs",
          ],
        },
      ],
      certifications: [
        {
          id: uuidv4(),
          name: "Certified Kubernetes Administrator (CKA)",
          issuer: "Cloud Native Computing Foundation",
          date: "2022",
        },
        {
          id: uuidv4(),
          name: "AWS DevOps Engineer - Professional",
          issuer: "Amazon Web Services",
          date: "2021",
        },
      ],
      sectionOrder: ["summary", "experience", "education", "projects", "skills", "certifications"],
    },
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    profession: "Data Science",
    description: "Analytics-focused template showcasing statistical modeling, Python/R, and business impact.",
    icon: "📊",
    color: "from-emerald-500 to-teal-500",
    tags: ["Analytics", "Statistics", "SQL"],
    resumeData: {
      personalInfo: {
        name: "Sofia Rodriguez",
        email: "sofia.rodriguez@email.com",
        phone: "+1 (555) 369-2580",
        location: "New York, NY",
        linkedin: "https://linkedin.com/in/sofiarodriguez",
        github: "https://github.com/sofiarodriguez",
        website: "",
      },
      summary: "Data Scientist with 5 years of experience turning complex datasets into actionable business insights. Expertise in A/B testing, causal inference, and predictive modeling.",
      experience: [
        {
          id: uuidv4(),
          company: "FinTech Analytics",
          position: "Senior Data Scientist",
          location: "New York, NY",
          startDate: "Apr 2021",
          endDate: "",
          current: true,
          description: [
            "Built credit risk model using gradient boosting, improving loan default prediction AUC from 0.72 to 0.89",
            "Designed A/B testing framework used by 10+ product teams, running 50+ experiments quarterly",
            "Automated reporting pipeline saving 20 hours/week of analyst time using Python and Airflow",
          ],
        },
      ],
      education: [
        {
          id: uuidv4(),
          institution: "Columbia University",
          degree: "Master of Science",
          field: "Statistics",
          location: "New York, NY",
          startDate: "Sep 2017",
          endDate: "May 2019",
          gpa: "3.85/4.0",
          courses: ["Statistical Learning", "Bayesian Analysis", "Time Series", "Causal Inference"],
        },
      ],
      skills: {
        Languages: ["Python", "R", "SQL", "Scala"],
        "ML Libraries": ["scikit-learn", "XGBoost", "LightGBM", "statsmodels", "Prophet"],
        "Data Tools": ["Spark", "Airflow", "dbt", "Tableau", "Looker"],
        Cloud: ["AWS (S3, Redshift, SageMaker)", "GCP (BigQuery)", "Snowflake"],
      },
      projects: [],
      certifications: [],
      sectionOrder: ["summary", "experience", "education", "skills", "certifications"],
    },
  },
  {
    id: "frontend",
    name: "Frontend Developer",
    profession: "Frontend Development",
    description: "UI/UX focused template highlighting React expertise, design systems, and performance.",
    icon: "🎨",
    color: "from-pink-500 to-rose-500",
    tags: ["React", "TypeScript", "CSS"],
    resumeData: {
      personalInfo: {
        name: "Jamie Park",
        email: "jamie.park@email.com",
        phone: "+1 (555) 147-2583",
        location: "Portland, OR",
        linkedin: "https://linkedin.com/in/jamiepark",
        github: "https://github.com/jamiepark",
        website: "https://jamiepark.design",
      },
      summary: "Frontend Engineer passionate about crafting pixel-perfect, accessible UIs with a focus on performance and delightful user experiences.",
      experience: [
        {
          id: uuidv4(),
          company: "DesignSystems Co.",
          position: "Senior Frontend Engineer",
          location: "Portland, OR",
          startDate: "Jun 2021",
          endDate: "",
          current: true,
          description: [
            "Built and maintained component library used by 15+ product teams with 200+ components and 98% accessibility coverage",
            "Improved Lighthouse performance score from 62 to 94 through code splitting, lazy loading, and critical CSS",
            "Migrated legacy Angular app to Next.js, reducing bundle size by 45% and improving TTI by 2.3s",
          ],
        },
      ],
      education: [
        {
          id: uuidv4(),
          institution: "Portland State University",
          degree: "Bachelor of Science",
          field: "Computer Science",
          location: "Portland, OR",
          startDate: "Sep 2015",
          endDate: "Jun 2019",
          gpa: "",
          courses: [],
        },
      ],
      skills: {
        "Core Web": ["HTML5", "CSS3", "TypeScript", "JavaScript (ES2024)"],
        Frameworks: ["React 19", "Next.js 15", "Vue 3", "Svelte"],
        "Styling & UI": ["Tailwind CSS", "Radix UI", "Framer Motion", "CSS Modules"],
        Testing: ["Vitest", "Playwright", "Testing Library", "Storybook"],
        Build: ["Vite", "Webpack", "Turbopack", "esbuild"],
      },
      projects: [
        {
          id: uuidv4(),
          name: "DesignKit UI",
          description: "Open-source accessible component library",
          technologies: ["React", "TypeScript", "Radix UI", "Storybook"],
          github: "https://github.com/jamiepark/designkit",
          bullets: [
            "1.2k GitHub stars with 30+ contributors and weekly npm downloads of 5k+",
            "100% WCAG 2.1 AA compliant with full keyboard navigation and screen reader support",
          ],
        },
      ],
      certifications: [],
      sectionOrder: ["summary", "experience", "education", "projects", "skills", "certifications"],
    },
  },
  {
    id: "product-manager",
    name: "Product Manager",
    profession: "Product Management",
    description: "Impact-driven PM template with OKRs, user metrics, and cross-functional leadership.",
    icon: "📋",
    color: "from-blue-500 to-sky-400",
    tags: ["Strategy", "Roadmap", "Metrics"],
    resumeData: {
      personalInfo: {
        name: "Taylor Kim",
        email: "taylor.kim@email.com",
        phone: "+1 (555) 753-9514",
        location: "Chicago, IL",
        linkedin: "https://linkedin.com/in/taylorkim",
        github: "",
        website: "",
      },
      summary: "Strategic Product Manager with 7 years delivering B2B SaaS products from 0→1 and growing them to $50M+ ARR. Data-driven decision maker with a track record of shipping beloved features.",
      experience: [
        {
          id: uuidv4(),
          company: "SaaS Platform Inc.",
          position: "Senior Product Manager",
          location: "Chicago, IL",
          startDate: "Jan 2021",
          endDate: "",
          current: true,
          description: [
            "Led 0-to-1 launch of Analytics Dashboard, driving 35% increase in platform stickiness (DAU/MAU)",
            "Managed $8M product budget and 12-person cross-functional team (engineering, design, data)",
            "Reduced customer churn by 22% through discovery research identifying and addressing 3 critical pain points",
          ],
        },
      ],
      education: [
        {
          id: uuidv4(),
          institution: "Northwestern University",
          degree: "Master of Business Administration",
          field: "Technology Strategy",
          location: "Evanston, IL",
          startDate: "Sep 2016",
          endDate: "Jun 2018",
          gpa: "",
          courses: [],
        },
      ],
      skills: {
        "Product Tools": ["Jira", "Linear", "Figma", "Notion", "Productboard"],
        Analytics: ["Mixpanel", "Amplitude", "Looker", "SQL", "Google Analytics"],
        Methodologies: ["Agile / Scrum", "Shape Up", "Jobs-to-be-Done", "OKRs", "Design Thinking"],
      },
      projects: [],
      certifications: [
        {
          id: uuidv4(),
          name: "Certified Product Manager (CPM)",
          issuer: "Product School",
          date: "2020",
        },
      ],
      sectionOrder: ["summary", "experience", "education", "skills", "certifications"],
    },
  },
];
