import { Octokit } from "octokit";
import { config } from "../config/index.js";

const octokit = new Octokit({ auth: config.github.token });
const owner = config.github.owner;
const repo = config.github.repo;

export async function getFileContent(path: string, ref = "main"): Promise<string> {
  const { data } = (await octokit.rest.repos.getContent({ owner, repo, path, ref })) as any;
  return Buffer.from(data.content, "base64").toString("utf-8");
}

export async function getRepoTree(ref = "main"): Promise<string[]> {
  const { data } = await octokit.rest.git.getTree({ owner, repo, tree_sha: ref, recursive: "true" });
  return data.tree.filter((t: any) => t.type === "blob").map((t: any) => t.path!);
}

export async function createPullRequest(
  title: string,
  body: string,
  patch: string,
  filePath: string,
  baseBranch = "main"
): Promise<string> {
  const branchName = `auto-fix/${Date.now()}`;

  const { data: baseRef } = await octokit.rest.git.getRef({ owner, repo, ref: `heads/${baseBranch}` });
  await octokit.rest.git.createRef({ owner, repo, ref: `refs/heads/${branchName}`, sha: baseRef.object.sha });

  const { data: currentFile } = (await octokit.rest.repos.getContent({ owner, repo, path: filePath, ref: baseBranch })) as any;

  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: filePath,
    message: `fix: ${title}`,
    content: Buffer.from(patch).toString("base64"),
    branch: branchName,
    sha: currentFile.sha,
  });

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: `🤖 Auto-fix: ${title}`,
    body: `## AI-Generated Fix\n\n${body}\n\n---\n*Generated by Self-Healing Platform*`,
    head: branchName,
    base: baseBranch,
  });

  return pr.html_url;
}

export async function getCodeOwners(filePath: string): Promise<string[]> {
  try {
    const content = await getFileContent("CODEOWNERS");
    const lines = content.split("\n").filter((l: string) => !l.startsWith("#") && l.trim());
    for (const line of lines.reverse()) {
      const [pattern, ...owners] = line.trim().split(/\s+/);
      if (filePath.match(new RegExp(pattern.replace(/\*/g, ".*")))) return owners;
    }
  } catch { /* no CODEOWNERS file */ }
  return [];
}

