apiVersion: v1
kind: ConfigMap
metadata:
  name: codecrafter-config
  namespace: codecrafter
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/codecrafter"
  SPRING_DATASOURCE_USERNAME: "cc_user"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "cc_rabbit"
  SPRING_RABBITMQ_VIRTUAL_HOST: "/"
  MINIO_ENDPOINT: "http://minio:9000"
  FRONTEND_URL: "https://codecrafter.dev"
  JWT_ACCESS_EXPIRY_MINUTES: "15"
  JWT_REFRESH_EXPIRY_DAYS: "7"
  SANDBOX_ENABLE_SECCOMP: "true"
